#!/bin/sh
##SBATCH --partition=supporters
#SBATCH --time=50:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=12
#SBATCH --job-name="TOPHAT"
#SBATCH --output=slurm.log
#SBATCH --mail-user=jbard@buffalo.edu
#SBATCH --mail-type=ALL
##SBATCH --requeue
#Specifies that the job will be requeued after a node failure.
#The default is that the job will not be requeued.

vflag=off
input=
genome=
gtf=
while getopts v:i:g:o:x:1:2 opt
do
    case "$opt" in
      v)  vflag=on;;
      x)  genome=$OPTARG;;
      o)  output=$OPTARG;;
      1)  input1=$OPTARG;;
      2)  input2=$OPTARG;;
      g)  gtf=$OPTARG;;
      \?)		# unknown flag
      	  echo >&2 \
	  "usage: $0 [-v] [-x genome] [-g gtf] [-o output] [-1 R1.fastq -2 R2.fastq]"
	  exit 1;;
    esac
done
shift `expr $OPTIND - 1`

echo "SLURM_JOBID="$SLURM_JOBID
echo "SLURM_JOB_NODELIST"=$SLURM_JOB_NODELIST
echo "SLURM_NNODES"=$SLURM_NNODES
echo "SLURMTMPDIR="$SLURMTMPDIR

cd $SLURM_SUBMIT_DIR
echo "working directory = "$SLURM_SUBMIT_DIR

module load tophat/2.0.7
module load samtools/0.1.19
module load bowtie/2-2.0.5    
module load bedtools/2.17.0

echo "Input: $input"
echo "Genome: $genome"
echo "output: $output"
echo "gtfFile: $gtf"

module list

tophat -G $gtf -p 8 --fusion-search -o $output $genome $input1 $input2
ulimit -s unlimited

#
echo "All Done!"
