#!/bin/sh

#[jbard@rush:/projects/mjbuck/Buck_Lab_Members/jbard/RSEM-Rose/RSEM_MS/FASTQ]$ for i in $(ls *Rep1_1* | cut -f1 -d"_"); do echo $i ; sbatch /projects/mjbuck/Scripts/slurm-rsem -g /projects/mjbuck/Buck_Lab_Members/jbard/RSEM-Rose/R
#[jbard@rush:/projects/mjbuck/Buck_Lab_Members/jbard/RSEM-Rose/RSEM_MS/FASTQ]$ for i in $(ls *Rep2_1* | cut -f1 -d"_"); do echo $i ; sbatch /projects/mjbuck/Scripts/slurm-rsem -g /projects/mjbuck/Buck_Lab_Members/jbard/RSEM-Rose/R


vflag=off
input=
genome=
fastq1=
fastq2=
while getopts v:a:b:o:g: opt
do
    case "$opt" in
      v)  vflag=on;;
      g)  genome=$OPTARG;;
      o)  output=$OPTARG;;
      a)  fastq1=$OPTARG;;
      b)  fastq2=$OPTARG;;
      \?)		# unknown flag
      	  echo >&2 \
	  "usage: $0 [-v] [-g genome] [-a fastq1] [-b fastq2] [-o output]"
	  exit 1;;
    esac
done
shift `expr $OPTIND - 1`

##SBATCH --partition=general-compute
#SBATCH --time=36:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=12
#SBATCH --job-name="TOPHAT"
#SBATCH --output=slurm.log
#SBATCH --mail-user=jbard@buffalo.edu
#SBATCH --mail-type=ALL
##SBATCH --requeue
#Specifies that the job will be requeued after a node failure.
#The default is that the job will not be requeued.


# rsem-calculate-expression -p 8 \--paired-end [fastq] [fastq] [genome] [output]

echo "SLURM_JOBID="$SLURM_JOBID
echo "SLURM_JOB_NODELIST"=$SLURM_JOB_NODELIST
echo "SLURM_NNODES"=$SLURM_NNODES
echo "SLURMTMPDIR="$SLURMTMPDIR

cd $SLURM_SUBMIT_DIR
echo "working directory = "$SLURM_SUBMIT_DIR


# Load any modules here

module load samtools/0.1.19
module load bowtie/1.1.1   
module load R/3.1.2
module load rsem/1.2.20

echo "Input: $input"
echo "Genome: $genome"
echo "output: $output"

module list

rsem-calculate-expression -p 12 --paired-end $fastq1 $fastq2 $genome $output


ulimit -s unlimited
#

#
echo "All Done!"
